config/routes.rb
Rails.application.routes.draw do
  resources :bloggers

end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :set_blogger, only: [:show, :edit, :update, :destroy]

  # GET /bloggers
  # GET /bloggers.json
  def index
    @bloggers = Blogger.all
  end

  # GET /bloggers/1
  # GET /bloggers/1.json
  def show
  end

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end

  # GET /bloggers/1/edit
  def edit
  end

  # POST /bloggers
  # POST /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)

    respond_to do |format|
      if @blogger.save
        format.html { redirect_to @blogger, notice: 'Blogger was successfully created.' }
        format.json { render :show, status: :created, location: @blogger }
      else
        format.html { render :new }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggers/1
  # PATCH/PUT /bloggers/1.json
  def update
    respond_to do |format|
      if @blogger.update(blogger_params)
        format.html { redirect_to @blogger, notice: 'Blogger was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogger }
      else
        format.html { render :edit }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end




  # DELETE /bloggers/1
  # DELETE /bloggers/1.json
  def destroy
    @blogger.destroy
    respond_to do |format|
      format.html { redirect_to bloggers_url, notice: 'Blogger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = Blogger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogger_params
      params.require(:blogger).permit(:name, :age, :gender, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/views/bloggers/_form.html.erb
<%= form_for(@blogger) do |f| %>
  <% if @blogger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
      <% @blogger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.check_box :gender %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing Blogger</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogger %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggers.each do |blogger| %>
      <tr>
        <td><%= blogger.name %></td>
        <td><%= blogger.age %></td>
        <td><%= blogger.gender %></td>
        <td><%= blogger.address %></td>
        <td><%= link_to 'Show', blogger %></td>
        <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
        <td><%= link_to 'Destroy', blogger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogger', new_blogger_path %>

app/views/bloggers/new.html.erb
<h1>New Blogger</h1>

<%= render 'form' %>

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blogger.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @blogger.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @blogger.gender %>
</p>

<p>
  <strong>Address:</strong>
  <%= @blogger.address %>
</p>

<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>